theme = "melange"

[editor]
line-number = "relative"
mouse = false
cursorline = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true
display-signature-help-docs = true

[editor.statusline]
left = ["mode", "spinner",  "file-name","version-control",]

[keys.normal]
C-s = ":w"

[keys.insert]
  "C-[" = "normal_mode"
