git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  commit:
    signOff: true
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
      - bold
  border: single
