#!bin/bash

#launch terminal
super + Return
  st
#launch terminal as float
super + {_,shift +}Return
  {st, bspc rule -a \* -o state=floating sticky=on layer=above rectangle=720x360+600+26 && st}

super + z
  alacritty
#your prefered browser
super + w
  firefox
#launch vs  code
super + c
  flatpak run com.visualstudio.code
# Open/close dashboard
alt + space
  rofi -show drun

#Volume control
XF86AudioMute
  exec pactl set-sink-mute @DEFAULT_SINK@ toggle
XF86AudioLowerVolume
  exec pactl set-sink-volume @DEFAULT_SINK@ -5%
XF86AudioRaiseVolume
  exec pactl set-sink-volume @DEFAULT_SINK@ +5%
#mute control
XF86AudioMicMute
  amixer set Capture toggle
# Brightness control
XF86MonBrightnessUp
  exec brightnessctl set +5%
XF86MonBrightnessDown
  exec brightnessctl set 5%-

# Close App
super + {_,shift + }q
	bspc node -{c,k}

#exit bspwm
super + shift + e
  bspc quit
# Restart bspwm
super + shift + r
  bspc wm -r

# Split horizontal, vertical or cancel
super + {h,v,q}
	bspc node -p {east,south,cancel}

# Preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# Fullscreen or Monocle
super + f
  bspc desktop -l next

super + shift + f
  bspc node -t "~"fullscreen

# Toggle beetwen floating & tiled
super + space
  bspc node -t "~"{floating,tiled}

super + {p,t}
  bspc node -t "~"{pseudo_tiled,tiled}

# Set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# Send the window to another edge of the screen
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# Change focus to next window, including floating window
alt + {_,shift + }Tab
	bspc node -f {next.local,prev.local}

# # Switch workspace
# ctrl + alt + {Left,Right}
# 	bspc desktop -f {prev.local,next.local}

# Switch to last opened workspace
super + {Tab,grave}
	bspc {node,desktop} -f last

# Send focused window to another workspace
super + {_,shift + }{1-9}
	bspc {desktop -f,node -d} '^{1-8}'

# Expanding windows
super + control + {Left,Right,Up,Down}
	bspc node -z {left -20 0,right 20 0,top 0 -20,bottom 0 20}
	
## Shrinking windows
super + alt + {Left,Right,Up,Down}
	bspc node -z {left 20 0,right -20 0,top 0 20,bottom 0 -20}
	
## Move floating windows
super + shift + {h,j,k,l}
	bspc node -v {-20 0,0 20,0 -20,20 0}
