version: 2
root-markers:
  - .git/
lint-debounce: 1s
commands:
  - command: hx
    arguments:
      - ${INPUT}
    title: config

tools:
  stylua: &stylua
    format-command: "stylua --search-parent-directories --stdin-filepath ${INPUT} -"
    format-stdin: true
    root-markers:
      - stylua.toml
      - .stylua.toml

  selene: &selene
    prefix: "selene"
    lint-source: "selene"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-command: "selene --display-style quiet -"
    lint-formats:
      - "%f:%l:%c: %trror%m"
      - "%f:%l:%c: %tarning%m"
      - "%f:%l:%c: %tote%m"

  luacheck: &luacheck
    prefix: "luacheck"
    lint-source: "luacheck"
    lint-stdin: true
    lint-command: "luacheck --codes --no-color --quiet -"
    lint-ignore-exit-code: true
    lint-formats:
      - "%.%#:%l:%c: (%t%n) %m"
    root-markers:
      - ".luacheckrc"

  prettier: &prettier
    format-can-range: true
    format-command: "prettier --stdin --stdin-filepath ${INPUT} ${--range-start:charStart} ${--range-end:charEnd} ${--tab-width:tabSize} ${--use-tabs:!insertSpaces}"
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  jq_lint: &jq_lint
    prefix: "jq"
    lint-source: "jq"
    lint-command: "jq"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-offset: 1
    lint-formats:
      - "%m at line %l, column %c"

  jq_format: &jq_format
    format-command: "jq"
    format-stdin: true

languages:
  lua:
    - <<: *stylua
    - <<: *selene
    - <<: *luacheck
  markdown:
    - <<: *prettier
  json:
    - <<: *jq_lint
    - <<: *jq_format
