#!/bin/env bash

killall sxhkd
killall polybar
killall feh
sxhkd &
polybar &
feh --bg-center --bg-fill "$XDG_CONFIG_HOME/bspwm/stat.jpg"&
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,gr
xsetroot -cursor_name crosshair &

bspc subscribe monitor | while read -r line; do
	case $line in
	monitor_add* | monitor_geometry*)
		if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
			bspc monitor "$(bspc query -M | sed -n 1p)" -d 00 04
			bspc monitor "$(bspc query -M | sed -n 2p)" -d 01 05
			bspc monitor "$(bspc query -M | sed -n 3p)" -d 02 06
			bspc monitor "$(bspc query -M | sed -n 4p)" -d 03 07
		elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
			bspc monitor "$(bspc query -M | sed -n 1p)" -d 00 03 07
			bspc monitor "$(bspc query -M | sed -n 2p)" -d 01 04 08
			bspc monitor "$(bspc query -M | sed -n 3p)" -d 02 05 09
		else
			bspc monitor -d 1 2 3 4 5 6 7 8
		fi
		;;
	*) ;;
	esac
done &

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 5
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

bspc rule -a firefox state=tiled
bspc rule -a Zathura state=tiled
