#!/usr/bin/env bash

export XCURSOR_THEME=Bibata-Modern-Classic
export XCURSOR_SIZE=18
export XDG_CURRENT_DESKTOP=River
export XDG_SESSION_DESKTOP=River
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export BEMENU_BACKEND=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=1
export GDK_BACKEND="wayland,x11,*"
export GTK_USE_PORTAL=1
export WLR_NO_HARDWARE_CURSORS=1

keyboard="pc105"
# keyboard="keyboard-1-1-AT_Translated_Set_2_keyboard"
riverctl keyboard-layout -model $keyboard "us,gr"
riverctl keyboard-layout -model $keyboard -options 'grp:switch,grp:alt_shift_toggle,grp_led:scroll,caps:ctrl_modifier' 'us,gr'

killall waybar
killall wl-clipboard
killall swaybg
killall wl-paste

# Autostart
# riverctl spawn "nm-applet --indicator"
# riverctl spawn "blueman-applet"
riverctl spawn "swaybg -i /usr/share/backgrounds/f40/default/f40-01-day.png"
riverctl spawn "waybar"
riverctl spawn "wl-clipboard"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
# Clipboard History
riverctl spawn "wl-paste --type text --watch cliphist store"  #Stores only text data
riverctl spawn "wl-paste --type image --watch cliphist store" #Stores only image data
riverctl spawn "wlr-randr --output eDP-1 --scale 1.00"

# Variables
terminal="kitty"
browser="firefox"
mod="Mod4"

# My Mappings

riverctl map normal $mod Return spawn "$terminal"
riverctl map normal $mod Z spawn "foot"
riverctl map normal Alt Shift focus-view next
riverctl map normal $mod W spawn "$browser"
riverctl map normal $mod C spawn "flatpak run com.visualstudio.code"
riverctl map normal $mod M spawn "bash -c 'grim -g \"\$(slurp)\" \"$HOME/Pictures/Screenshots/\$(date +%Y-%m-%dT%H-%M-%S).png\"'"

riverctl map normal Alt space spawn "rofi -show drun"

riverctl map normal $mod Q close
riverctl map normal $mod+Shift E exit
riverctl map normal $mod+Control F toggle-float
riverctl map normal $mod+Shift F toggle-fullscreen
riverctl map normal $mod+Shift R spawn "$HOME/.config/river/init >/dev/null"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Alt Tab focus-view next
riverctl map normal Super K focus-view previous

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

for i in $(seq 1 9); do
	# Tags are basically workspaces, but different
	tags=$((1 << ("$i" - 1)))
	# Move focus to Tag(Workspace)
	riverctl map normal $mod "$i" set-focused-tags $tags
	# Move view(window) to Tag(Workspace)
	riverctl map normal $mod+Shift "$i" set-view-tags $tags
	# Show view(window) from specified tag on current tag(workspace)
	riverctl map normal $mod+Control "$i" toggle-focused-tags $tags
	# Show focused view(window) on specified tag(workspace)
	riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
	riverctl map $mode None XF86Eject spawn 'eject -T'

	riverctl map $mode None XF86AudioRaiseVolume spawn "pamixer -i 5 "
	riverctl map $mode None XF86AudioLowerVolume spawn "pamixer -d 5 "
	riverctl map $mode None XF86AudioMute spawn "pamixer --toggle-mute "

	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext spawn 'playerctl next'

	riverctl map $mode None XF86MonBrightnessUp spawn "brightnessctl set +10% "
	riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 10%- "
done

# Mouse binds
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

# $mod+0 to focus all tags
# $mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

riverctl map-switch normal lid close "swaylock -f"

# $mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Space zoom

# Move all these binds to a floating mode, since that's where the work
riverctl declare-mode floating
riverctl map normal $mod+Alt F enter-mode floating

# -repeat makes the bind repeatable, while it not released
# {H,J,K,L} to resize views by 25
riverctl map -repeat floating None H resize horizontal -25
riverctl map -repeat floating None J resize vertical 25
riverctl map -repeat floating None K resize vertical -25
riverctl map -repeat floating None L resize horizontal 25

# Control+{H,J,K,L} to move views by 25
riverctl map -repeat floating Control H move left 25
riverctl map -repeat floating Control J move down 25
riverctl map -repeat floating Control K move up 25
riverctl map -repeat floating Control L move right 25

# Shift+{H,J,K,L} to snap views to screen edges
riverctl map floating Shift H snap left
riverctl map floating Shift J snap down
riverctl map floating Shift K snap up
riverctl map floating Shift L snap right

riverctl map floating None Escape enter-mode normal

# Focus windows with $mod h/j/k/l
riverctl map normal $mod+Control H focus-view left
riverctl map normal $mod+Control J focus-view down
riverctl map normal $mod+Control K focus-view up
riverctl map normal $mod+Control L focus-view right

#Focus windows with $mod Arrow keys
riverctl map normal $mod Left focus-view left
riverctl map normal $mod Down focus-view down
riverctl map normal $mod Up focus-view up
riverctl map normal $mod Right focus-view right

# $mod+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal $mod+Control N focus-view next
riverctl map normal $mod+Control P focus-view previous

# Swap views(windows) with $mod+Shift h/j/k/l
riverctl map normal $mod+Shift Left swap left
riverctl map normal $mod+Shift Down swap down
riverctl map normal $mod+Shift Up swap up
riverctl map normal $mod+Shift Right swap right

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# $mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# $mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

riverctl declare-mode resize
riverctl map normal $mod+Alt R enter-mode resize
# {Up,Right,Down,Left} to change layout orientation
riverctl map resize None Up send-layout-cmd rivertile "main-location top"
riverctl map resize None Right send-layout-cmd rivertile "main-location right"
riverctl map resize None Down send-layout-cmd rivertile "main-location bottom"
riverctl map resize None Left send-layout-cmd rivertile "main-location left"
#
# $mod+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map resize $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map resize $mod L send-layout-cmd rivertile "main-ratio +0.05"

# $mod+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map resize $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map resize $mod+Shift L send-layout-cmd rivertile "main-count -1"
riverctl map resize None Escape enter-mode normal
#
# $mod+Period and Super+Comma to focus the next/previous output(Monitor/Screen)
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# $mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

#  ███████████              ████
# ░░███░░░░░███            ░░███
#  ░███    ░███  █████ ████ ░███   ██████   █████
#  ░██████████  ░░███ ░███  ░███  ███░░███ ███░░
#  ░███░░░░░███  ░███ ░███  ░███ ░███████ ░░█████
#  ░███    ░███  ░███ ░███  ░███ ░███░░░   ░░░░███
#  █████   █████ ░░████████ █████░░██████  ██████
# ░░░░░   ░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░  ░░░░░░

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add ssd

# riverctl rule-add -app-id "floorp" tags $((1 << (1 - 1)))
# riverctl rule-add -app-id "firefox" tags $((1 << (1 - 1)))
# riverctl rule-add -app-id "Code" tags $((1 << (2 - 1)))
# riverctl rule-add -app-id "special-go" tags $((1 << (2 - 1)))
# riverctl rule-add -app-id "dev.zed.Zed" tags $((1 << (2 - 1)))
# riverctl rule-add -app-id "org.gnome.Nautilus" tags $((1 << (3 - 1)))
# riverctl rule-add -app-id "Thunar" tags $((1 << (3 - 1)))
# riverctl rule-add -app-id "org.libretro.RetroArch" tags $((1 << (4 - 1)))
# riverctl rule-add -app-id "Celeste.bin.x86_64" tags $((1 << (4 - 1)))
# riverctl rule-add -app-id "hollow_knight.x86_64" tags $((1 << (4 - 1)))
# riverctl rule-add -title "Brawlhalla" tags $((1 << (4 - 1)))
# riverctl rule-add -app-id "citra-qt" tags $((1 << (4 - 1)))
# riverctl rule-add -app-id "es-de" tags $((1 << (4 - 1)))
# riverctl rule-add -app-id "steam" tags $((1 << (4 - 1)))
# riverctl rule-add -app-id "Ferdium" tags $((1 << (5 - 1)))
# riverctl rule-add -app-id "Webcord" tags $((1 << (6 - 1)))
# riverctl rule-add -app-id "obsidian" tags $((1 << (7 - 1)))
# riverctl rule-add -title "Brawlhalla" fullscreen
# riverctl rule-add -app-id "org.pwmt.zathura" fullscreen
# riverctl rule-add -app-id "mpv" fullscreen
# riverctl rule-add -app-id "feh" fullscreen
# riverctl rule-add -app-id "org.libretro.RetroArch" fullscreen
# riverctl rule-add -app-id "es-de" fullscreen
# riverctl rule-add -title "Special Offers" float # Steam
# riverctl rule-add -title "Friends List" float   # Steam
# riverctl rule-add -title "Steam Settings" float # Steam
# riverctl rule-add -app-id "steam" -title "Brawlhalla" float
# riverctl rule-add -app-id "galculator" float
# riverctl rule-add -app-id "org.kde.kcalc" float
# riverctl rule-add -app-id "blueman-manager" float
# riverctl rule-add -app-id "org.kde.kdeconnect.app" float
# riverctl rule-add -app-id "nm-connection-editor" float
# riverctl rule-add -app-id "org.kde.polkit-kde-authentication-agent-1" float
# riverctl rule-add -app-id "polkit-gnome-authentication-agent-1" float
# riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
# riverctl rule-add -app-id 'GParted' float
# riverctl rule-add -app-id 'nwg-look' float
# riverctl rule-add -app-id 'firefox' -title 'Picture-in-Picture' float
# riverctl rule-add -app-id 'floorp' -title 'Picture-in-Picture' float
# riverctl rule-add -title 'gtk*' float
# riverctl rule-add -app-id 'xdg-desktop-portal-gtk' float
# riverctl rule-add -app-id float float
# riverctl rule-add -title "popup title with spaces" float
# riverctl rule-add -title "zoom" float
# riverctl rule-add -title "Picture-in-Picture" float

# Set background and border color
riverctl background-color 0x002B36
riverctl border-width 2
riverctl border-color-focused 0x47B4C5
riverctl border-color-unfocused 0xA5A5A5

riverctl set-repeat 30 300
riverctl default-attach-mode top
riverctl focus-follows-cursor always
riverctl hide-cursor timeout 60000 # 60 Seconds in milliseconds
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme "Bibata-Modern-Classic" 18

# Touchpad Settings
# Get device name from riverctl list-inputs
touchpad="pointer-1267-12553-ELAN2204:00_04F3:3109_Touchpad"
riverctl input $touchpad tap enabled
# riverctl input "pointer-2-7-SynPS/2_Synaptics_TouchPad" tap enabled
riverctl input $touchpad accel-profile flat
riverctl input $touchpad natural-scroll enabled
riverctl input $touchpad disable-while-typing enabled
riverctl input $touchpad disable-while-trackpointing enabled
riverctl input $touchpad tap-button-map left-middle-right
#
# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 3 -outer-padding 3 -main-ratio 0.5 -main-count 1 &
