let mapleader = " "
set belloff=all
set spelllang=el,en
set spell
set laststatus=2
set smartindent
set smartcase
set scrolloff=3
set sidescrolloff=3
set cursorline
set nonumber
set relativenumber
set splitbelow
set splitright
set numberwidth=2
set termguicolors
set timeout
set timeoutlen=400
set nocompatible
set linebreak
set pumheight=10
set expandtab
set shiftwidth=2
set clipboard=unnamedplus
set softtabstop=2
set wildoptions=pum
set completeopt+=menuone,popup,noselect,fuzzy
set diffopt=filler,internal,hiddenoff,algorithm:histogram,indent-heuristic,linematch:60,vertical
set listchars+=extends:>,precedes:<
set fillchars+=foldopen:,foldclose:
set path+=**
set langmap=ΑA,ΒB,ΨC,ΔD,ΕE,ΦF,ΓG,ΗH,ΙI,ΞJ,ΚK,ΛL,ΜM,ΝN,ΟO,ΠP,QQ,ΡR,ΣS,ΤT,ΘU,ΩV,WW,ΧX,ΥY,ΖZ,αa,βb,ψc,δd,εe,φf,γg,ηh,ιi,ξj,κk,λl,μm,νn,οo,πp,qq,ρr,σs,τt,θu,ωv,ςw,χx,υy,ζz
if executable('rg')
  set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --color=never\ --glob\ \!.git
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

if has('win32') && executable('pwsh.exe')
  set shell=pwsh.exe
  set shellxquote=
  set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
endif

set statusline=
set statusline+=%{pathshorten(expand('%:p'))}
set statusline+=%m
set statusline+=\ [%{&ff}]
set statusline+=%=
set statusline+=\ [%{&fileencoding}]
set statusline+=\ %y
set statusline+=\ l:%l/%L
set statusline+=\ c:%c
set statusline+=\ [%p%%]

colorscheme habamax
set viminfo+=n~/.config/vim/viminfo
packadd! comment
packadd! nohlsearch
packadd! matchit
packadd! justify
